== 盲注SQL注入

盲注SQL注入是一种通过向数据库提出真/假问题并根据应用程序的响应来确定答案的SQL注入攻击。当Web应用程序配置为显示通用错误信息，但未修复易受SQL注入攻击的代码时，通常会使用这种攻击方式。

=== 区别

让我们首先了解普通SQL注入和盲注SQL注入之间的区别。在普通SQL注入中，数据库的错误信息会显示出来，并提供足够的信息来了解查询的工作方式。或者，在基于UNION的SQL注入中，应用程序不会直接在网页上反映信息。因此，在没有显示任何内容的情况下，您需要开始基于真/假陈述向数据库提问。这就是为什么盲注SQL注入更难被利用的原因。

盲注SQL注入有几种不同的类型：基于内容的盲注和基于时间的盲注。


=== 示例

在这种情况下，我们尝试基于唯一ID向数据库提出布尔问题。例如，假设我们有以下URL：`https://my-shop.com?article=4`
在服务器端，此查询将被翻译为：

----
SELECT * FROM articles WHERE article_id = 4
----

当我们想要利用这一点时，我们将URL更改为：`https://shop.example.com?article=4 AND 1=1`
这将被翻译为：

----
SELECT * FROM articles WHERE article_id = 4 and 1 = 1
----

如果浏览器返回的页面与使用`https://shop.example.com?article=4`时相同，那么您知道该网站容易受到盲注SQL注入攻击。
如果浏览器返回页面未找到或其他内容，您知道盲注SQL注入可能不起作用。
现在，您可以更改SQL查询并进行测试，例如：`https://shop.example.com?article=4 AND 1=2`，由于查询返回false，因此不会返回任何内容。

我们如何实际利用这一点？上面我们只向数据库提出了一个简单的问题，但您也可以使用以下URL：`https://shop.example.com?article=4 AND substring(database_version(),1,1) = 2`

大多数时候，您首先需要找出使用的数据库类型。根据数据库类型，您可以找到数据库的系统表，从而枚举数据库中存在的所有表。有了这些信息，您就可以开始从所有表中获取信息，并能够转储数据库。
请注意，如果数据库的权限设置正确（意味着无法使用从Web应用程序连接到数据库的用户查询系统表），则此方法可能不起作用。


Another way is called a time-based SQL injection, in this case you will ask the database to wait before returning
the result. You might need to use this if you are totally blind. This means there is no difference between the response data.
To achieve this kind of SQL injection you could use:

----
article = 4; sleep(10) --
----
